#!/bin/bash

readpass() {
if [ -z $FTP_PASS ]; then
echo "no FTP_PASS password found"
exit -1
fi
password=$FTP_PASS
}

ftp-put() {
ncftpput -R -v -u eressea-de -p $password ftp.eressea.de . de en images includes *.* .ht*
}

weex-put() {
mkdir -f ~/.weex
weexrc=~/.weex/weexrc
dir=`pwd`

if [ -e $weexrc ]; then
echo "existing $weexrc, take a backup"
rcbackup="$weexrc.orig"
mv $weexrc $rcbackup
fi

cat > $weexrc <<EOF
# automatically created by travis-build
[default]
AsciiFile = {
*.html
*.ssi
*.txt
*.shtml
*.php
*.js
*.py
}

IgnoreLocalFile = {
*~
}

[eressea]
DestDir = /
SrcDir = $dir
Password = $password
HostName = ftp.eressea.de
LoginName = eressea-de
IgnoreRemoteDir = /public
IgnoreLocalDir = s
IgnoreLocalDir = .git
EOF

chmod 600 $weexrc
weex -m eressea
}

cleanup() {
rm -f $weexrc
if [ ! -z $rcbackup ]; then
echo "restoring $weexrc from backup"
mv $rcbackup $weexrc
fi
}

trap cleanup 0
set -e
readpass
#weex-put
ftp-put
cleanup
