#!/bin/bash

htmltidy() {
HERE=`pwd`
for REPLY in {de,en}/*.php ; do
  echo $REPLY
  DIR=`dirname $REPLY`
  FILE=`basename $REPLY`
  cd $DIR
  php $FILE | tidy -q -o /dev/null
  cd $HERE
done
}

set -e
htmltidy
echo "Done."

