#!/bin/bash

readpass() {
if [ -z $FTP_PASS ]; then
echo "no FTP_PASS password found"
exit -1
fi
password=$FTP_PASS
}

ftp-put() {
lftp -u eressea-de,$password ftp.eressea.de -e 'mirror -c -e -R source . ; exit'
}

cleanup() {
echo "Aborted."
}

htmltidy() {
HERE=`pwd`
for REPLY in source/??/*.php ; do
  echo $REPLY
  DIR=`dirname $REPLY`
  FILE=`basename $REPLY`
  cd $DIR
  php $FILE | tidy -q -o /dev/null
  cd $HERE
done
}

trap cleanup 0
set -e
htmltidy
readpass
ftp-put
echo "Done."

